# Release: https://github.com/iscander01/excalidraw/releases/tag/v1.1.11111010101010101010100101
# Workflow URL: https://github.com/iscander01/excalidraw/actions/runs/17859212786
# Commit: https://github.com/iscander01/excalidraw/commit/420a95102931e6ba926134dc5f0e005b8ead2e0c
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/iscander01/excalidraw@sha256:d2a448c298c224d6495424956449d09b4c9c3704079776f3be33a09650e98ab2
    ports:
      - '3000:80'
