# Release: https://github.com/iscander01/excalidraw/releases/tag/v0.0.0111010101001
# Workflow URL: https://github.com/iscander01/excalidraw/actions/runs/16722032936
# Commit: https://github.com/iscander01/excalidraw/commit/eb16705737363f4f2c9e3c9bd9b168e4a4630359
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/iscander01/excalidraw@sha256:4879e9355c5e991fff8e9ad72c9be125fc30c259fb3c465e9e1ceb4c11cb8194
    ports:
      - '8080'
